### ISSUE TITLE
JdbiUnitOfWork - 1.2 release is not found in maven

### ISSUE THREAD

**Issue by harshach** [isopropylcyanide/dropwizard-jdbi-unitofwork#123]
Hi @isopropylcyanide, thanks for this project. Are you continuing to maintain the project and do the new releases? The version is set to 1.2 in your examples, but the Maven public repositories don't have this version. Appreciate if there is any new release and if you can point me to it. Thank you

**Comment by isopropylcyanide** [comment]
Hello @harshach , I routinely address vulnerabilities and dependenabot merges. However, I never realized that the project is used outside. If you are interested, you can bump up the version, or else I can do it and cut a release.

**Comment by isopropylcyanide** [comment]
Hello @harshach , I routinely address vulnerabilities and dependenabot merges. However, I see that the project is not available on Maven Central. 

Let me push a release.

**Comment by harshach** [comment]
Thank you @isopropylcyanide

**Comment by isopropylcyanide** [comment]
@harshach Running into some issues talking to the key server for sonatype to publish releases. I suspect it's my work laptop firewall that's blocking all outbound. I'll try to push one in a couple of days once I arrange a non work laptop.

Please allow me some time.
